### PR TITLE
Home Page: Events/Networking Section

### PR DESCRIPTION
**Pull request by onlyhasbi**
## Description
PR for issues Home Page: Events/Networking Section

## Screenshot / Screen Recording
ReactJS-Indonesia

### CODE REVIEW

**Review by mhaidarhanif — CHANGES_REQUESTED** [review]
Almost there. Use easy import icons, not using manual SVG files, from a package such as lucide or anything that's close to the design

**Comment by onlyhasbi** [comment]
> Almost there. Use easy import icons, not using manual SVG files, from a package such as lucide or anything that's close to the design

can you please pointing in the file change, which one should need to change ? thanks

**Comment by onlyhasbi** [comment]
> Almost there. Use easy import icons, not using manual SVG files, from a package such as lucide or anything that's close to the design

i've been using lucide-react for an icon

Screenshot 2024-07-10 at 22 31 39
Screenshot 2024-07-10 at 22 32 01

except this one
Screenshot 2024-07-10 at 22 32 13

**Review by mhaidarhanif — APPROVED** [review]
All good and simpler now

**Pull request merged**
